### ISSUE TITLE
Authenticate Clients

### ISSUE THREAD

**Issue by dennis-tra** [dennis-tra/punchr#13]
Depending on how many clients we want to distribute we may want to secure the API somehow.

Ideas:

1. Pre-generate the client identities and only allow requests from those
2. Some simple basic auth
3. Just don't do it :D

**Comment by dennis-tra** [comment]
Added API-Key authorization logic to go-client and server

**Comment by mxinden** [comment]
:rocket: 

Guessing this is the commit that introduced it? https://github.com/dennis-tra/punchr/commit/83264d76a09e8d0e92532b370292a039a6a23b3c

//CC @elenaf9 in case you want to look into this. No opinion on whether to prioritize it over the QUIC effort or not.

**Comment by dennis-tra** [comment]
Yup, that's right 👍 

I've basically only added an `api_key` field to the registration request :)

**Comment by mxinden** [comment]
Cool! Sounds good to me. Thanks @elenaf9!
