### ISSUE TITLE
Check if client is behind a NAT

### ISSUE THREAD

**Issue by dennis-tra** [dennis-tra/punchr#21]
panic if it's not

**Comment by AnomalRoil** [comment]
Is panicking really a good idea here? 

A client running this on their laptop might be jumping from a NAT home network to a non-NAT work network to another NAT library network.
This feels like a metric worse reporting, or maybe just a reason to slow down reporting until the network changes to a NAT one.

**Comment by dennis-tra** [comment]
> Is panicking really a good idea here?

Not really, you're right! This is a quite old issue. Right now, the client will report all its own listen addresses and successful NAT port mappings which should give enough data to draw conclusions about NAT'd-ness.
