### ISSUE TITLE
rust-client/: Ensure client discovered public addrs before punching

### ISSUE THREAD

**Issue by mxinden** [dennis-tra/punchr#32]
For a hole punch to succeed, the local node needs to know its public (/external) address.

The current implementation depends on learning its external address through the relay node. In case the remote client initiates the DCUtR protocol before the relay node told us our public addresses the hole punch fails.

Consider connecting to some random node first, to learn ones public address before initiating the connection to the remote client and relay.

Related code in the rust-libp2p DCUtR client:

https://github.com/libp2p/rust-libp2p/blob/66c275520d8cf56152cce9a1c24bb4e2c42e0833/protocols/dcutr/examples/client.rs#L192-L223

//CC @elenaf9 I remember we talked about this, but I fail to recall what the result of that conversation was. Do you think the above might be an issue today?

**Comment by mxinden** [comment]
//CC @dennis-tra as I am curious how the Golang implementation solves this. Just in case you know it already. Otherwise I will dive into the Golang code myself.

**Comment by dennis-tra** [comment]
The go-client connects to PL's bootstrap nodes and blocks execution until it has learned its public addresses (this doesn't take long). There's this `WaitForPublicAddr` function:

https://github.com/dennis-tra/punchr/blob/dbad93c29b54580b40d1726ef61bd2ea6e923cb8/cmd/client/host.go#L134

I've copied that bit from the [go holepunch implementation](https://github.com/libp2p/go-libp2p/blob/aa6d051e651fb1fc42c7f4d98023a3b6c01df6a0/p2p/protocol/holepunch/svc.go#L92).
