### ISSUE TITLE
`HolePunchAttempt::started_at` is optional in proto but required by server

### ISSUE THREAD

**Issue by elenaf9** [dennis-tra/punchr#7]
Per `punchr.proto`, the field  `HolePunchAttempt::started_at` is optional. On the server side however it returns an error if that field is not present: 
https://github.com/dennis-tra/punchr/blob/f94de18ad88b9e06b7f781a66303bfd9d33563fd/cmd/server/grpc.go#L158-L160
Was this done intentionally? 

From my side we can treat the `started_at` field as required, but then this should be marked correctly in the proto file.

**Comment by dennis-tra** [comment]
True dat! Let's mark it as required if it's also no problem on the rust side :) I'll push an update
