### ISSUE TITLE
Track relay version for remote connection

### ISSUE THREAD

**Issue by dennis-tra** [dennis-tra/punchr#8]
- track whether the connection uses circuit relay v1 or v2
    - not exposed in go-lib2p
    - rust-libp2p needs to be compiled with support for only either

https://pl-strflt.notion.site/NAT-Hole-Punching-Measurement-0bc0399711824bb79603841bb00935ee

**Comment by mxinden** [comment]
I would expect the fraction of remote peers behind circuit relay v1 relays to become negligible. Thus, I don't think we have to track this. In case we see a lot of connection failures to relay servers from the Rust client, we might want to reconsider.

@elenaf9 let me know in case I am missing something.
